from object_recognition.models.abstract import ObjectRecognition
from object_recognition.models.detr_resnet import DetrResnetObjectRecognition
from object_recognition.models.mask2former import Mask2FormerObjectRecognition
from object_recognition.models.yolos import YolosObjectRecognition
